version: '3.8'

services:
  job-application-ai:
    build: .
    container_name: job-application-ai
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - LINKEDIN_USERNAME=${LINKEDIN_USERNAME}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - CAPTCHA_API_KEY=${CAPTCHA_API_KEY}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
    # Add GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      - ollama
    # Uncomment to use browser in non-headless mode with VNC
    # ports:
    #   - "5900:5900"  # VNC port for viewing browser
  
  # Ollama service for local LLM processing
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    # Add GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    restart: unless-stopped
    # Add a healthcheck to ensure Ollama is ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Add command to pull mistral model on startup
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull mistral &&
             wait"

volumes:
  ollama_data: 