version: '3.8'

services:
  job-application-ai:
    build: .
    container_name: job-application-ai
    privileged: true
    volumes:
      - ./:/app  # Mount the entire project directory
    environment:
      - LINKEDIN_USERNAME=${LINKEDIN_USERNAME}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - CAPTCHA_API_KEY=${CAPTCHA_API_KEY}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
    # Add GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Keep container running but don't start app
    command: tail -f /dev/null
    restart: unless-stopped
    depends_on:
      - ollama
    # Uncomment to use browser in non-headless mode with VNC
    # ports:
    #   - "5900:5900"  # VNC port for viewing browser
  
  # Ollama service for local LLM processing
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    privileged: true
    volumes:
      - ollama_data:/root/.ollama
    # Add GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    restart: unless-stopped
    # Add a healthcheck that also pulls the model on first run
    healthcheck:
      test: 
        - CMD-SHELL
        - |
          if [ ! -f /tmp/model_pulled ]; then
            echo "Pulling mistral model..."
            ollama pull mistral && touch /tmp/model_pulled
          fi
          curl -f http://localhost:11434/api/tags || exit 1
      interval: 30s
      timeout: 300s
      retries: 5
      start_period: 10s

volumes:
  ollama_data: 